#version: "3.8"

services:
  # Primer servicio: app
  app:
    build: . # Construye una nueva imagen a partir del Dockerfile en el directorio actual
    image: node-image # Usa una imagen llamada "node-image" (debe existir previamente)
    tty: true # Habilita una terminal interactiva
    container_name: node-image # Nombre del contenedor que vemos en consola
    ports:
      - "3000:3000" # Mapea puerto 3000 del contenedor al host
    volumes:
      - .:/app/ # Monta el directorio actual en /app dentro del contenedor
    command: sh /app/executable.sh # Comando que se ejecutará al iniciar el contenedor

  # #Segundo servivio template redis
  # redis:
  #   image: redis:latest             # Usa la última imagen de Redis
  #   container_name: redis           # Nombre del contenedor que vemos en consola
  #   ports:
  #     - "6379:6379"                 # Mapea puerto 6379 del contenedor al host

  #Tercer servivio template nginx
  nginx:
    image: nginx:latest # Usa la última imagen de Nginx
    container_name: nginx # Nombre del contenedor que vemos en consola
    ports:
      - "8080:80" # Mapea puerto 80 del contenedor al host
      - "443:443" # Mapea puerto 443 del contenedor al host
